### ISSUE TITLE
Streamlit conda support migration

### ISSUE THREAD

**Issue by astrojams1** [mcsorkun/ChemPlot-web#1]
Please see https://discuss.streamlit.io/t/managing-your-streamlit-dependencies-using-conda/12346. I tried to submit a PR but I do not have access. You need to remove `conda.txt`, `conda-channels.txt`, and `requirements.txt` and then create an `environment.yml` file with the following contents:

```
channels:
  - conda-forge
dependencies:
  - libgcc=5.2.0
  - rdkit
  - streamlit==0.78.0
  - chemplot==0.1.2
  - mordred==1.2.0
  - Pillow==8.1.0
  - pandas==1.1.3
  - scipy==1.5.2
  - numpy==1.19.2
  - bokeh==2.2.3
  - gspread==3.7.0
  - oauth2client==4.1.3
  - oauthlib==3.1.0
  - pytz==2020.5
```

**Comment by dajtmullaj** [comment]
Thank you for the feedback! 
We updated the repository!
