### ISSUE TITLE
ChemPlot service not working

### ISSUE THREAD

**Issue by marinusvanbeuningen** [mcsorkun/ChemPlot-web#10]
Dear Mcsorkun,

On Synday I have been able to use Chemplot-web after the service was back online. But after about an hour the web-app stopped. https://chemplot.streamlit.app/ .

Can you solve this issue.

Thanks

Marinus van Beuningen

**Comment by mcsorkun** [comment]
Dear @marinusvanbeuningen ,

The app is working again. I recommend using ChemPlot Python library, instead of the web app for large-scale applications. 
You can find docs below, it contains how to install and some code examples.

https://chemplot.readthedocs.io/en/latest/
