### ISSUE TITLE
Question about upload CSV format

### ISSUE THREAD

**Issue by hirose125** [mcsorkun/ChemPlot-web#14]
Dear Murat,

Thank you for the wonderful app. I would like to try using this app. 
Are there any sample CSVs or demonstrations of how to actually use it?

The CSV file I prepared did not work. 
Could you please tell me what kind of CSV format I should prepare?

**Comment by dajtmullaj** [comment]
Here are some example datasets from the ChemPlot library: https://github.com/mcsorkun/ChemPlot/tree/main/chemplot/data. 
The CSV file must at least contain a column of SMILES which the app can the process. 
You can also indicate a target column if you are interested in using tailored similarity.
