### ISSUE TITLE
chemplot.streamlit.app Web App is down

### ISSUE THREAD

**Issue by nztao** [mcsorkun/ChemPlot-web#15]
![image](https://github.com/mcsorkun/ChemPlot-web/assets/109556492/33932fa2-60d5-4502-a146-7865ed8fdc44)

After uploading a dataset with a 'Name', 'SMILES', and hot-encoded binary classifier column, the ChemPlot Web App crashed and is now down.

**Comment by dajtmullaj** [comment]
The app is now running again. Currently we do not process datasets with more than 5000 instances. 
For complex uses we recommend using the ChemPlot library directly (https://github.com/mcsorkun/ChemPlot).
