### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by NupurJain3898** [mcsorkun/ChemPlot-web#3]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://mcsorkun-chemplot-web-web-app-chemplot-jrrecy.streamlitapp.com/mcsorkun/chemplot-web/main/web_app_chemplot.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by dajtmullaj** [comment]
Thank you for letting us know. Will look into the problem.
I am closing the issue for the moment.
