### ISSUE TITLE
Error while trying to run chemplot app (https://chemplot.streamlit.app/)

### ISSUE THREAD

**Issue by basterb** [mcsorkun/ChemPlot-web#7]
Hello, 

I am very interested in running the chemplot app since I do not have experience with python. However, everytime I try to run (using different devices/browsers) the app I get an error message "Error running app. If this keeps happening, please [contact support](https://github.com/mcsorkun/chemplot-web/issues/new)."

Am I doing something wrong or is the app not functional anymore?

Thank you,

Bas

**Comment by mcsorkun** [comment]
Hello Bas,

ChemPlot web is up again. Thank you for the report.

https://chemplot.streamlit.app/

**Comment by basterb** [comment]
Dear Murat, 

Thank you for your response. 

ChemPlot web was working for a couple of days, but it seems to be offline again. Could you help me once again? 

Thank you.

**Comment by mcsorkun** [comment]
Hello @basterb, it is working now.

**Comment by basterb** [comment]
@mcsorkun, thank you. Much appreciated!
